// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdfcoluythzrcwjpygfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZmNvbHV5dGh6cmN3anB5Z2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjU3MjYsImV4cCI6MjA3MzcwMTcyNn0.tfjVU65vl-EjtkY-ZAk15UoSITVrINP6Nuuxh2JVHtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});